version: '3.7'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  web:
    build: .
    command: python3 app.py runserver 0.0.0.0:5001
    volumes:
      - .:/code
    ports:
      - "5001:5001"
    depends_on:
      - db